resources:
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: manishas_jfrog_github   # replace with your integration
      path: manishas-jfrog/jfrog-pipelines-hello-world    # replace with your repository name
      branches:
        include: master
        
  - name: myPropertyBag
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1


pipelines:
  - name: hello_world_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          timeoutSeconds: 60
          inputResources:
            - name: someRepo
        execution:
          onExecute:
            - echo $res_myRepo_commitSha
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_myRepo_commitSha            
            - echo "Previous run ID is $prev_runid"

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Hello world"
            - echo $current_runid

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: myPropertyBag
        execution:
          onExecute:
            - echo "Hello world"
            - echo $current_runid
            - add_pipeline_variables prev_runid=$run_id
            - write_output myPropertyBag commitSha=$commitSha runID=$current_runid


